global using System.Collections;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.IO;
global using System.Runtime.CompilerServices;
global using System.Windows;
global using System.Windows.Input;
global using LibGit2Sharp;
global using Microsoft.Win32;